name: machine
favicon: null
layout_spectrum: 0.87877
typography_spectrum: 0.25979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#fffffd'
    - '#6f5c3c'
    - '#d0af7a'
    - '#fee0a2'
  brandStrength: 0.9393166892696172
  lightness: 0.9302636007778347
  saturation: 0.9624846170190722
  rhythmicContrast: 0.6027051389683038
purpose: []
